tbl <- read.table("household_power_consumption.txt",header=TRUE,sep=';')
tb <- na.omit(tbl[as.Date(tbl$Date, "%m/%d/%Y")== as.Date("02/02/2007","%m/%d/%Y") | as.Date(tbl$Date, "%m/%d/%Y")== as.Date("02/01/2007","%m/%d/%Y"),])
tb$Date = format(as.Date(tb$Date,"%m/%d/%Y"),"%a")
g_range <- range(0,2)
d_range <- range(tb$Date)
png(filename="plot2.png", height=480, width=480, bg="white")
plot(tb$Global_active_power, type="o", axes=FALSE, ann=FALSE)
axis(1, at=1:3, labels= c(d_range[2], d_range[1], "Sat"))
axis(2, las=1, at= 4*0:g_range[2])
box()
lines(tb$Global_active_power, type="o", pch=22, lty=2, col="red")
title(main="Global Active Power", col.main="red", font.main=4)
title(xlab= "Days")
title(ylab= "Global Active Power (in Kilowatts)")
dev.off()
